"""FrontendBridge: communication layer between the AI agent and the frontend.

Exposes a synchronous `send(action, payload)` used by tools (e.g.
ComponentTool) to dispatch a command, plus the original async `call(...)`
for callers that want to await a real frontend response directly.

Phase 4.1 - MCP Foundation:
    FrontendBridge now supports two transport modes, selected by its
    `mode` constructor argument / property:

        - "mock" (the default, and the only mode used until a later phase
          switches it): send()'s behavior is completely unchanged from
          before this phase - it still decides internally, based on
          whether a frontend is connected over WebSocket, whether to mock
          the response or forward it over that WebSocket and await a real
          reply. Nothing about this path was touched.
        - "mcp": send() forwards the command to an MCPClient
          (mcp/client.py) instead of the WebSocket path above. MCPClient
          is a placeholder only (see its module docstring) - no real MCP
          protocol, transport, or server exists yet. This mode exists so
          the rest of the pipeline (ComponentTool, CanvasTool, and
          everything upstream of them) never has to change when a real
          MCP server eventually replaces the mock: only bridge.py's mode
          and MCPClient's internals will.

    Every existing caller of `send()` is unaffected: the default mode is
    "mock", so `FrontendBridge()` / the module-level `bridge` instance
    below behaves exactly as it did before this phase.

Phase 4.2 - MCP Command Translation Layer:
    Every command send() handles is now also run through an
    MCPCommandBuilder (mcp/command_builder.py), which translates Bridge's
    native {"action", "payload"} shape into the standardized
    {"method", "params"} shape a real MCP server is expected to speak.
    This is pure translation, not communication - it does not change what
    "mock" mode returns:
        - "mock": the translated MCP command is built and logged/printed
          for visibility only; the response returned to the caller is
          exactly the same mock response as before this phase.
        - "mcp": the translated MCP command (not the raw Bridge command) is
          what actually gets passed to MCPClient.send().
    A translation failure (an action with no registered MCP method) never
    breaks "mock" mode - it's caught and logged, and the mock response is
    still returned unchanged.

Callers never need to check `connected` themselves - `send()` always
returns a dict, and its "mode" field says which path was taken: "mock" or
"real" for the WebSocket path (unchanged), "mcp" for the MCP path (new).

The frontend connects to the /ws/frontend endpoint. Each real call sends
{"id", "function", "args"} and waits for a matching {"id", "success", "result"/"error"}
reply from the frontend.
"""

import asyncio
import json
import logging
import os
import uuid
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from mcp.client import MCPClient
from mcp.command_builder import MCPCommandBuilder

logger = logging.getLogger(__name__)

router = APIRouter()

# Every MCP command (mock or real) is appended here, one JSON object per
# line (JSON Lines, despite the ".json" extension) - a lightweight stand-in
# for a real UI connection: replaying this file's lines against the
# addComponent/connectComponents/etc. methods is what a real frontend would
# have done live. Resolved relative to this file, not the caller's cwd, so
# it lands in the same place regardless of where main.py is run from.
_UI_COMMANDS_PATH = os.path.join(os.path.dirname(__file__), "ui_commands.json")

# In-memory mirror of the same commands, for callers (graph/workflow.py's
# Executor Agent) that want "every MCP command generated by this request"
# without re-reading the file. Module-level because `bridge` below is a
# module-level singleton shared by every tool - see get_recorded_commands()/
# clear_recorded_commands().
_recorded_commands: List[Dict[str, Any]] = []


def _record_mcp_command(mcp_command: dict) -> None:
    """Print `mcp_command`, keep it in memory, and append it to ui_commands.json.

    The file write is append-only - never rewrites or truncates - so a demo
    session accumulates a full, ordered history of every command the UI
    would have received. A write failure is logged, not raised: this is a
    visibility side effect, it must never turn an otherwise-successful
    bridge call into a failure.
    """
    print(f"[MCP Command Builder] {mcp_command}")
    _recorded_commands.append(mcp_command)
    try:
        with open(_UI_COMMANDS_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps(mcp_command) + "\n")
    except OSError as exc:
        logger.error("Failed to write MCP command to %s: %s", _UI_COMMANDS_PATH, exc)


def get_recorded_commands() -> List[Dict[str, Any]]:
    """Return every MCP command recorded so far this process, in order."""
    return list(_recorded_commands)


def clear_recorded_commands() -> None:
    """Reset the in-memory MCP command log - called once per request by graph/workflow.py.

    Only clears the in-memory mirror; ui_commands.json itself is never
    truncated, so the on-disk history still spans the whole session.
    """
    _recorded_commands.clear()

# The only bridge modes send() knows how to handle. Kept as a plain tuple
# (not an enum) to match this module's existing style - callers pass a
# plain string, exactly like every other config value in this codebase.
_VALID_MODES = ("mock", "mcp")

# The mode every FrontendBridge starts in unless told otherwise. Must stay
# "mock" - Phase 4.1 only adds the "mcp" path, it never turns it on by
# default, so the AI agent keeps working exactly as before.
_DEFAULT_MODE = "mock"


class FrontendBridge:
    def __init__(
        self,
        timeout: float = 5.0,
        mode: str = _DEFAULT_MODE,
        mcp_client: Optional[MCPClient] = None,
        command_builder: Optional[MCPCommandBuilder] = None,
    ):
        self.timeout = timeout
        self._socket: WebSocket | None = None
        self._pending: dict[str, asyncio.Future] = {}
        self._mode = self._validate_mode(mode)
        self._mcp_client = mcp_client if mcp_client is not None else MCPClient()
        self._command_builder = command_builder if command_builder is not None else MCPCommandBuilder()

    @staticmethod
    def _validate_mode(mode: str) -> str:
        if mode not in _VALID_MODES:
            raise ValueError(f"Unknown bridge mode {mode!r}; expected one of {_VALID_MODES}")
        return mode

    @property
    def mode(self) -> str:
        """The transport send() currently uses: "mock" or "mcp"."""
        return self._mode

    @mode.setter
    def mode(self, value: str) -> None:
        self._mode = self._validate_mode(value)

    @property
    def connected(self) -> bool:
        return self._socket is not None

    async def register(self, websocket: WebSocket) -> None:
        await websocket.accept()
        self._socket = websocket
        try:
            while True:
                message = await websocket.receive_json()
                self._resolve(message)
        except WebSocketDisconnect:
            pass
        finally:
            if self._socket is websocket:
                self._socket = None

    def _resolve(self, message: dict) -> None:
        future = self._pending.pop(message.get("id"), None)
        if future is not None and not future.done():
            future.set_result(message)

    async def call(self, function: str, **kwargs) -> dict:
        """Call a frontend function over WebSocket and await its response.

        Raises:
            ConnectionError: no frontend is connected.
            TimeoutError: the frontend didn't respond in time.
            RuntimeError: the frontend reported the call failed.
        """
        if self._socket is None:
            raise ConnectionError("No frontend connected")

        call_id = str(uuid.uuid4())
        future = asyncio.get_running_loop().create_future()
        self._pending[call_id] = future

        try:
            await self._socket.send_text(json.dumps({"id": call_id, "function": function, "args": kwargs}))
            response = await asyncio.wait_for(future, timeout=self.timeout)
        finally:
            self._pending.pop(call_id, None)

        if not response.get("success", False):
            raise RuntimeError(response.get("error") or f"{function} failed")
        return response.get("result")

    def send(self, action: str, payload: dict) -> dict:
        """Build a standardized command and dispatch it through the current mode.

        Which transport handles the command is decided by `self.mode`,
        never by the caller:
            - "mock" (default): unchanged from before Phase 4.1 - see
              _send_via_mock().
            - "mcp": forwarded to MCPClient - see _send_via_mcp().

        Returns:
            {
                "success": bool,
                "message": str,
                "command": {"action": str, "payload": dict}      # mode "mock"/"real"
                         | {"method": str, "params": dict},       # mode "mcp" (Phase 4.2)
                "mode": "mock" | "real" | "mcp",
                "result": ...,  # present when success is True and mode != "mock"
                "error": ...,   # present when success is False and mode != "mock"
            }
        """
        if self._mode == "mcp":
            return self._send_via_mcp(action, payload)
        return self._send_via_mock(action, payload)

    def _build_and_print_mcp_command(self, action: str, payload: dict) -> None:
        """Translate `action`/`payload` into its MCP form and record it.

        Phase 4.2: this is visibility only, ahead of a real MCP server
        existing - the translated command is never sent anywhere from
        here, and any failure (e.g. an action with no registered MCP
        method) is caught and logged rather than propagated, so it can
        never affect the mock response _send_via_mock() returns. "Record"
        means printed and appended to ui_commands.json (see
        _record_mcp_command()) - simulating what a real UI would have
        received, since none is attached in mock mode.
        """
        try:
            mcp_command = self._command_builder.build(action, payload).to_dict()
        except ValueError as exc:
            logger.warning("MCP command translation skipped for action=%r: %s", action, exc)
            return

        logger.info("MCP command translation (mock mode, not sent): %s", mcp_command)
        _record_mcp_command(mcp_command)

    def _send_via_mock(self, action: str, payload: dict) -> dict:
        """Mock/WebSocket transport - the original send() body, plus (Phase
        4.2) printing the command's MCP translation for visibility.

        Decides internally, based on whether a frontend is currently
        connected over WebSocket, whether to:
            - return a mock response describing the command that would be
              sent (local development / testing - no frontend attached), or
            - forward the command to the connected frontend over WebSocket
              and return its real response.

        The response returned here is exactly what it was before Phase
        4.2 - translating and printing the MCP command is a side effect
        only, it never changes what's returned.
        """
        command = {"action": action, "payload": payload}
        self._build_and_print_mcp_command(action, payload)

        if not self.connected:
            logger.info("Bridge command generated (mock mode): %s", command)
            return {
                "success": True,
                "message": "Bridge command generated",
                "command": command,
                "mode": "mock",
            }
        logger.info("Forwarding command to frontend (real mode): %s", command)
        try:
            result = asyncio.run(self.call(action, **payload))
        except Exception as exc:
            logger.error("Bridge command failed (real mode): %s - %s", command, exc)
            return {
                "success": False,
                "message": "Bridge command failed",
                "command": command,
                "mode": "real",
                "error": str(exc),
            }

        logger.info("Bridge command succeeded (real mode): %s", command)
        return {
            "success": True,
            "message": "Bridge command forwarded to frontend",
            "command": command,
            "mode": "real",
            "result": result,
        }
    def _send_via_mcp(self, action: str, payload: dict) -> dict:
        """MCP transport (Phase 4.1 foundation, Phase 4.2 translation - no
        real protocol yet).

        Translates the Bridge-native action/payload into a standardized
        MCP command (MCPCommandBuilder), then forwards *that* - not the
        raw action/payload - to self._mcp_client: connects it if needed,
        sends the translated command, and reads back its response.
        MCPClient is a placeholder (see mcp/client.py) - this method only
        wires bridge.py up to that interface so a real MCP server can
        replace it later without any change here.
        """
        raw_command = {"action": action, "payload": payload}

        try:
            mcp_command = self._command_builder.build(action, payload).to_dict()
        except ValueError as exc:
            logger.error("MCP command translation failed: %s - %s", raw_command, exc)
            return {
                "success": False,
                "message": "MCP command translation failed",
                "command": raw_command,
                "mode": "mcp",
                "error": str(exc),
            }

        logger.info("Forwarding translated MCP command (mcp mode): %s -> %s", raw_command, mcp_command)
        _record_mcp_command(mcp_command)
        try:
            if not self._mcp_client.is_connected():
                self._mcp_client.connect()
            self._mcp_client.send(mcp_command)
            response = self._mcp_client.receive()
        except Exception as exc:
            logger.error("MCP command failed: %s - %s", mcp_command, exc)
            return {
                "success": False,
                "message": "MCP command failed",
                "command": mcp_command,
                "mode": "mcp",
                "error": str(exc),
            }

        result = response.get("result") if isinstance(response, dict) else response
        logger.info("MCP command succeeded: %s", mcp_command)
        return {
            "success": True,
            "message": "Bridge command forwarded to MCP Client",
            "command": mcp_command,
            "mode": "mcp",
            "result": result,
        }
bridge = FrontendBridge()
@router.websocket("/ws/frontend")
async def frontend_socket(websocket: WebSocket):
    await bridge.register(websocket)
