"""FastAPI integration layer for the InnoIDE React frontend.

This module is a thin HTTP wrapper around the existing agent - it contains
no planning, execution, verification, or MCP-translation logic of its own.
Every request is handed to graph.run_workflow() (the same LangGraph
pipeline main.py's CLI already uses: Intent Agent -> Planner Agent ->
Executor Agent -> Verifier Agent -> Context Update), and the response is
built entirely from what that call already returns - the MCP commands in
state["mcp_commands"] (generated by the existing Bridge/MCPCommandBuilder,
unchanged) and the tool results in state["tool_results"].

Running this does not affect the CLI: main.py still runs run_workflow()
directly, in-process, with no dependency on this module or on a server
being up.
"""

import logging
import os
import threading

from fastapi import FastAPI, HTTPException, Request, UploadFile
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from api.models import AgentResponse, ExecuteRequest, HealthResponse, VoiceResponse
from context import context_engine
from graph import run_workflow

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(title="InnoIDE AI Agent API", version="1.0.0")

# The Context Engine is one process-wide session. A request that syncs the
# frontend canvas into it must run its whole workflow before another
# request can replace that canvas, so requests touching it run one at a time.
_workflow_lock = threading.Lock()

# Configurable via env var so this never hard-codes a production origin -
# comma-separated for more than one (e.g. a deployed URL plus local dev).
# Defaults to the standard React dev server port when unset.
_DEFAULT_ORIGIN = "http://localhost:3000"
_allowed_origins = [
    origin.strip()
    for origin in os.environ.get("INNOIDE_FRONTEND_ORIGIN", _DEFAULT_ORIGIN).split(",")
    if origin.strip()
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_origins,
    allow_credentials=True,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


def _agent_response_from_workflow(result: dict) -> dict:
    """Build the API's response body from one run_workflow() result, unchanged data only.

    Never invents or reshapes MCP command contents - "commands" is exactly
    state["mcp_commands"] as generated by the existing Bridge, and
    "results" is exactly state["tool_results"] as produced by the existing
    ToolExecutor/Verifier.
    """
    completed = result.get("status") == "completed"
    return {
        "status": "success" if completed else "error",
        "message": "Command executed successfully" if completed else (result.get("error") or "Command execution failed"),
        "commands": result.get("mcp_commands", []),
        "results": result.get("tool_results", []),
    }


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Reshape FastAPI's default {"detail": [...]} validation error into {"status", "message"}."""
    errors = exc.errors()
    raw_message = errors[0]["msg"] if errors else "Invalid request"
    message = raw_message.split("Value error, ", 1)[-1] if raw_message.startswith("Value error, ") else raw_message
    return JSONResponse(status_code=400, content={"status": "error", "message": message or "Invalid request"})


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
    """Reshape FastAPI's default {"detail": ...} HTTP error into {"status", "message"}."""
    return JSONResponse(status_code=exc.status_code, content={"status": "error", "message": str(exc.detail)})


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Catch anything unexpected: log the real traceback server-side, never send it to the client."""
    logger.exception("Unhandled error while handling %s %s", request.method, request.url.path)
    return JSONResponse(status_code=500, content={"status": "error", "message": "Internal server error"})


@app.get("/api/health", response_model=HealthResponse)
def health() -> dict:
    return {"status": "ok", "service": "InnoIDE AI Agent"}


@app.post("/api/agent/chat", response_model=AgentResponse)
def execute_command(request: ExecuteRequest) -> dict:
    """Run one natural-language command through the existing LangGraph agent.

    Pydantic's ExecuteRequest already rejects a missing/blank "command"
    (see its field_validator) before this function is even called - that
    validation error is caught by validation_exception_handler() above.
    """
    logger.info("[/api/agent/chat] command=%r", request.command)
    with _workflow_lock:
        if request.canvas_state is not None:
            # The frontend's canvas is the source of truth for this request.
            summary = context_engine.sync_from_canvas(request.canvas_state.model_dump())
            logger.info("[/api/agent/chat] canvas_state synced: %s", summary)
        result = run_workflow(request.command)
    return _agent_response_from_workflow(result)


@app.post("/api/agent/voice", response_model=VoiceResponse)
async def execute_voice_command(audio: UploadFile) -> dict:
    """Transcribe an uploaded audio clip, normalize it, then run it through the same agent.

        Audio -> Speech-to-Text -> Command Normalization -> LangGraph

    Reuses run_workflow() exactly as /api/agent/chat does, on the
    *normalized* text - there is no separate planning/execution path for
    voice. Normalization (command_normalizer.py) only corrects
    speech-recognition artifacts in component names against the real
    catalog (e.g. "NSP" -> "ESP32"); it never touches LangGraph, the
    Planner, the Executor, the Verifier, or the MCP Bridge.
    """
    from command_normalizer import UnresolvedComponentError, normalize_command
    from voice_input import transcribe_audio_bytes

    audio_bytes = await audio.read()
    transcript = transcribe_audio_bytes(audio_bytes)

    if not transcript:
        logger.warning("[/api/agent/voice] transcription failed for upload %r", audio.filename)
        return {"status": "error", "message": "Unable to transcribe audio"}

    try:
        normalized_command = normalize_command(transcript)
    except UnresolvedComponentError as exc:
        # A letters+digits token looked like an attempted technical
        # component code (e.g. "TH55") but nothing in the catalog was a
        # confident match - stop here, before run_workflow()/the Planner
        # ever runs, rather than invent a component from a guess.
        logger.warning("[/api/agent/voice] could not confidently resolve %r in transcript: %r", exc.unresolved_terms, transcript)
        return {"status": "error", "message": "Could not confidently identify component. Please repeat.", "transcript": transcript}

    logger.info("Original transcript: %s", transcript)
    logger.info("Normalized command: %s", normalized_command)

    if normalized_command is None:
        # normalize_command() returns None only when the transcript is
        # dominated by one word repeated an implausible number of times -
        # a speech-recognition failure, not a real command - so this stops
        # here, before run_workflow()/the Planner ever runs, instead of
        # executing whatever a "best effort" correction would have guessed.
        logger.warning("[/api/agent/voice] rejected a severely repetitive/corrupted transcript: %r", transcript)
        return {"status": "error", "message": "Speech not understood", "transcript": transcript}

    with _workflow_lock:
        result = run_workflow(normalized_command)
    response = _agent_response_from_workflow(result)
    response["transcript"] = transcript
    response["normalized_command"] = normalized_command
    return response


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("api.server:app", host="0.0.0.0", port=8001, reload=True)
